### ISSUE TITLE
Fork conda-build-all to conda-forge organization

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-build-all-feedstock#30]
I would like to suggest that the conda-build-all repository be forked and moved to the `conda-forge` organization.  

Currently the [repository](https://github.com/SciTools/conda-build-all) is under the SciTools organization.  Very few, if any, of the @conda-forge/core team has commit access to this repository which can create difficulties when changes need to be made.  Most recently a patch, SciTools/conda-build-all#83, needed to add support for conda 4.3 has been waiting for review and merging for quite some time.  Given how important this package for conda-forge in driving staged-recipes, I think it is only prudent that we be able to control timely updates.

**Comment by mwcraig** [comment]
I'm 👍  on this... SciTools/conda-build-all#87 fixes an issue with the 1.6.3 release of conda-env and should also be merged soonish.

**Comment by jakirkham** [comment]
Yeah, I'm ok with it too. Though was thinking about how we can probably write out `conda-build-all` entirely with the release of `conda-build` 3.x.

**Comment by marscher** [comment]
+1 for forking.

**Comment by scopatz** [comment]
+1 for forking as well

**Comment by msarahan** [comment]
🍴 

Although conda-build 3 should get rid of the need for it, it'll take time to adopt conda-build 3.

**Comment by jjhelmus** [comment]
I think we are in agreement then.  I apparently do not have permissions in the conda-forge organization to create new repository.  Can someone who does create a `conda-build-all` repo or update my permissions to allow repository creation?

**Comment by mwcraig** [comment]
I just changed your role to maintainer, can you please try again?

**Comment by ocefpaf** [comment]
Thanks for fixing that @mwcraig. @jjhelmus you should have the same rights as the other @conda-forge/core members. Let me know if you are still missing permissions so we can fix that.

**Comment by jjhelmus** [comment]
No change.  I'm still seeing "insufficient permission" when I go to create a new repository in the conda-forge organization.

**Comment by ocefpaf** [comment]
How about now?

**Comment by jjhelmus** [comment]
All fixed.  The conda-forge fork of `conda-build-all` is at https://github.com/conda-forge/conda-build-all.  I'll submit the PR from the SciTools repository shortly.

**Comment by ocefpaf** [comment]
Thanks for taking the lead on that one @jjhelmus!

**Comment by mwcraig** [comment]
Thanks @jjhelmus -- can you please grab SciTools/conda-build-all#87 too?

**Comment by jjhelmus** [comment]
> can you please grab SciTools/conda-build-all#87 too?

Done, conda-forge/conda-build-all#2

**Comment by jakirkham** [comment]
So it has been forked, we copied over the PRs, merged them, made a tag, and released it on conda-forge. I think it is safe to say this is done. Thanks everyone.
