### ISSUE TITLE
Packages missing in current linux-64 channels

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-build-all-feedstock#34]
_From @rainwoodman on February 9, 2017 9:52_

We are seeing this error if a recipe depends on other recipes in the same directory. This seem to have been fixed a while ago. We are using the combo of, and

    - conda install conda-build=2.0.10
    - conda install -c conda-forge conda-build-all=1.0*

_Copied from original issue: conda-tools/conda-build-all#80_

**Comment by jakirkham** [comment]
_From @rainwoodman on February 9, 2017 9:57_

Seems like if a dependency package is already uploaded to the channel, and thus not built, then we see this error.

**Comment by jakirkham** [comment]
Is this still an issue, @rainwoodman? I think the latest `conda-build-all` has all needed packages, but haven't gone back through the older ones.

**Comment by rainwoodman** [comment]
We haven't run into this issue in the last few months, so it is no longer affecting us. I don't recall a quick way to reproduce it.

**Comment by jakirkham** [comment]
Ok, if you do, please let us know. Going to close as this was likely resolved one way or another.
